name = "my-app"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-11"

kv_namespaces = [ 
    { binding = "POSTS", preview_id = "57782d2d126042f29dc5e0d03460956f" },
    { binding = "POST_FILES", preview_id = "f79de75abfad4f91bad5d24eeda195ad" },
    { binding = "TIMESTAMP_INDEX", preview_id = "08ff0d6214894b42bec91488727f84cd" },
]

[vars]
WORKERS_RS_VERSION = "0.0.7"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"


# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
